### ISSUE TITLE
Automate the  configuration and deployment step  for the CNCF-CI Bot

### ISSUE THREAD

**Issue by riaankleinhans** [cncf-infra/prow-config#87]
Automation of CNCF-CI Bot update
- [update-conformance-yaml.yml](https://github.com/cncf-infra/verify-conformance/blob/main/.github/workflows/update-conformance-yaml.yml) monitor the incoming release and create an updating PR when it is detected.
- Create a new workflow to monitor the merging of the PR from update-conformance-yaml.yml
    - When the PR merged the workflow run the [configuration and deployment](https://github.com/cncf-infra/prow-config/blob/master/infra/aws/README.org#configure-4) steps to complete the processs.

Only human action requier would be merging of the PRs    
    
## From [comment below](https://github.com/cncf-infra/prow-config/issues/87#issuecomment-1336654767) 
still working on this one

 add a Kubernetes ServiceAccount with patch+replace permissions for the deployment and configmap in the namespace
there is a way to get access to a Kubernetes service account, given an IAM role.

Changes include

https://github.com/cncf-infra/prow-config/compare/c1e51e4d996b2627b419ff522993e38455f685d7..ad7d32ec7aad04ac07e640c44eaf8f14d63eed0e
https://github.com/cncf-infra/aws-infra/compare/160f9564f662e51607c7bbcf149f0431eeb15288..c76fdd4418b8b1e499e4cd3df5055ecb9d2b97d2
https://github.com/cncf-infra/verify-conformance/compare/446f9de690932ae35868f5fa5a068d1a07e2de66..124b4a61be12ec904df5f0650ad654d6aa1937db

**Comment by BobyMCbobs** [comment]
Currently, the deployment of the cluster, Prow and verify-conformance are all management my hand in the org-mode document.
In order to simply and effectively automate the deployment of verify-conformance, the following changes are needed
- tangle once and tangle no more
- remove org-mode comments from YAML (tidy)
- remove org-mode YAML code blocks
- add a AWS IAM user to auth as, with read/write permissions to the cluster
- add a Kubernetes ServiceAccount with patch+replace permissions for the deployment and configmap in the namespace
- add a script to deploy the new version
- add a GitHub action to call the script
- add AWS auth credentials (or is there a better way) into a GitHub secret

considerations
- it may be required or easier to move the deployment definition to the _cncf-infra/verify-conformance_ repo
- move the cluster Terraform and related files to the _cncf-infra/aws-infra_ repo

**Comment by hh** [comment]
Do we need it on AWS or can we use Equinix?

**Comment by riaankleinhans** [comment]
> Do we need it on AWS or can we use Equinix?

That would help cut consumption of AWS credits.

**Comment by BobyMCbobs** [comment]
> Do we need it on AWS or can we use Equinix?

@hh, I think this is a separate consideration.

Regardless, it would take quite a bit of reworking

**Comment by BobyMCbobs** [comment]
Managed to build it together.

https://github.com/cncf-infra/verify-conformance/actions/runs/3616264241/jobs/6094049562

Whenever there's a merge on master, the bot will be built and deployed.

Things that I learned were not needed

- ~~tangle once and tangle no more~~ - i moved the configuration to the cncf-infra/verify-conformance repo
- ~~remove org-mode comments from YAML (tidy)~~ - ^
- ~~remove org-mode YAML code blocks~~ - ^
- ~~add a script to deploy the new version~~ - fits it right with the existing action
- ~~add a GitHub action to call the script~~ - ^
- ~~add AWS auth credentials (or is there a better way) into a GitHub secret~~ - using OIDC, short lived ephemeral tokens can be used instead via setting up a trust between a IAM role and a provider

still working on this one
- [ ] add a Kubernetes ServiceAccount with patch+replace permissions for the deployment and configmap in the namespace

there is a way to get access to a Kubernetes service account, given an IAM role.

Changes include
- https://github.com/cncf-infra/prow-config/compare/c1e51e4d996b2627b419ff522993e38455f685d7..ad7d32ec7aad04ac07e640c44eaf8f14d63eed0e
- https://github.com/cncf-infra/aws-infra/compare/160f9564f662e51607c7bbcf149f0431eeb15288..c76fdd4418b8b1e499e4cd3df5055ecb9d2b97d2
- https://github.com/cncf-infra/verify-conformance/compare/446f9de690932ae35868f5fa5a068d1a07e2de66..124b4a61be12ec904df5f0650ad654d6aa1937db

**Comment by riaankleinhans** [comment]
Good job @BobyMCbobs 
I'll keep this open till the fisrt 1.26 Conformance PR was evaluated by the bot on cncf/k8s-conformance.
